# Minimal tmux config

# Hide the status bar (normally at the bottom).
set -g status off

# New sessions:
# - Split the first window into left/right panes.
set-hook -g after-new-session 'split-window -h'

# Set inactive windows to muted gray and active window to true black.
# Just a shade too light
set -g window-style 'fg=#00ff00,bg=#111111'
set -g window-active-style 'fg=#00ff00,bg=#000000'

# pane border
set -g pane-border-style 'fg=#550000,bg=default'
set -g pane-active-border-style fg=green,bg=default

#set -g pane-border-style 'fg=colour235'
#set -g pane-active-border-style 'fg=#00ff00'

# message text
set-option -g message-style fg=colour166,bg=colour235

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange

# clock
set-window-option -g clock-mode-colour green #green

# Allows for faster key repetition
set -s escape-time 0

# Preserve truecolor output for inline ANSI renderers
set -g default-terminal "tmux-256color"
set -as terminal-features ",*:RGB"
