#!/bin/sh
#

cd ~/projects/LabDiscovery
SESSIONNAME=LabDiscovery

CHECK=$( tmux has-session -t $SESSIONNAME )

if [[ $? -eq 0 ]] ; then
    tmux -2 new-session -t "$SESSIONNAME"
    exit
fi


# Add sleeps between the split window events to make sure the prompts
# wrap correctly. I kid you not. If you set this too low, it will look
# like:
PANEWAIT=2

# Single window on left, 3 windows on right
tmux new-session -d -s "$SESSIONNAME"
sleep $PANEWAIT

tmux split-window -h  
sleep $PANEWAIT

tmux split-window -h  
sleep $PANEWAIT

tmux select-pane -t 0
sleep $PANEWAIT
tmux resize-pane -L 65 
sleep $PANEWAIT
tmux resize-pane -L 65 
sleep $PANEWAIT

# Now back to the central pane
tmux select-pane -t 1
sleep $PANEWAIT

tmux -2 new-session -t "$SESSIONNAME"
