#!/bin/sh
#
# This is designed to be run on a 1600x900 screen in gnome-terminal with
# Monospace Regular font at size 10 in full screen. No menubars, no
# titlebars.
#

cd ~/projects/lls_data
SESSIONNAME=lls

CHECK=$( tmux has-session -t $SESSIONNAME )

if [[ $? -eq 0 ]] ; then
    tmux -2 new-session -t "$SESSIONNAME"
    exit
fi

export PANEWAIT=0.3

tmux new-session -d -s "$SESSIONNAME" 
sleep $PANEWAIT

tmux split-window -h 
sleep $PANEWAIT
#tmux split-window -v
#sleep $PANEWAIT
#tmux select-pane -t 0
#sleep $PANEWAIT
#tmux split-window -h 
#sleep $PANEWAIT
#tmux select-pane -t 0
#sleep $PANEWAIT

# After the session loads, issue the command below with the left most
# pane focused
#resize-pane -L 65 
# Then clear the command line with:
# export PS1=; clear
#to get that 1-char wide left pane automate it here when you figure out
# how to get it to work from a script

tmux -2 new-session -t "$SESSIONNAME"

