#!/bin/sh
#
# This is designed to be run on a 1600x900 screen in gnome-terminal with
# Monospace Regular font at size 10 in full screen. No menubars, no
# titlebars.
#
# Built with tmux from source commit: 968296bb

cd ~/projects/mps-youtube
SESSIONNAME=mpsyt_edit

CHECK=$( tmux has-session -t $SESSIONNAME )

if [[ $? -eq 0 ]] ; then
    tmux -2 attach-session -d -t "$SESSIONNAME"
    exit
fi

# Add sleeps between the split window events to make sure the prompts
# wrap correctly. I kid you not. If you set this too low, it will look
# like:
PANEWAIT=2

tmux set-option remain-on-exit on

# Single window on left, 3 windows on right
tmux new-session -d -s "$SESSIONNAME" 'cmus --listen 192.168.0.70:5577'
#tmux new-session -d -s "$SESSIONNAME" 'bash'

tmux split-window -h  '~/projects/pulsemixer/pulsemixer'
sleep $PANEWAIT
tmux split-window -v 'sleep 1; play -c 2 -n synth brownnoise'

sleep $PANEWAIT
tmux split-window -v 'sleep 1; bash'

tmux -2 attach-session -d -t "$SESSIONNAME"
