#!/bin/sh
#

cd ~/projects/OhMyLegs
SESSIONNAME=OhMyLegs

CHECK=$( tmux has-session -t $SESSIONNAME )

if [[ $? -eq 0 ]] ; then
    tmux -2 new-session -t "$SESSIONNAME"
    exit
fi

#tmux set-option remain-on-exit on

# Single window on left, 3 windows on right
tmux new-session -d -s "$SESSIONNAME"

tmux split-window -h  
sleep 1

tmux split-window -h  
sleep 1

tmux select-pane -t 0
sleep 1
tmux resize-pane -L 65 
tmux resize-pane -L 65 

# Now back to the central pane
tmux select-pane -t 1

tmux -2 new-session -t "$SESSIONNAME"
