#!/bin/sh
#
# quad-window split
#

SESSIONNAME=tunnels

CHECK=$( tmux has-session -t $SESSIONNAME )

if [[ $? -eq 0 ]] ; then
    tmux -2 attach-session -t "$SESSIONNAME"
    exit
fi

# Add sleeps between the split window events to make sure the prompts
# wrap correctly. I kid you not. If you set this too low, it will look
# like the text is wrapping at width 60 even though the pane is width
# 80+
PANEWAIT=1

cd ~/projects/Titan/scripts/aws_ec2_control

tmux new-session -d -s "$SESSIONNAME" 

tmux split-window -v 
sleep $PANEWAIT
tmux split-window -h 
sleep $PANEWAIT
tmux split-window -h 
sleep $PANEWAIT
tmux split-window -h
sleep $PANEWAIT


# Switch back to top pain, split again
tmux select-pane -t 0
tmux split-window -h
sleep $PANEWAIT

tmux -2 attach-session -d -t "$SESSIONNAME"
