#!/bin/sh
#
# This is designed to be run on a 1600x900 screen in gnome-terminal with
# Monospace Regular font at size 10 in full screen. No menubars, no
# titlebars.
#
# Built with tmux from source commit: 968296bb

cd ~/Documents/auto_backup
SESSIONNAME=workflows

CHECK=$( tmux has-session -t $SESSIONNAME )

if [[ $? -eq 0 ]] ; then
    tmux -2 new-session -t "$SESSIONNAME"
    exit
fi

tmux set-option remain-on-exit on

# Add sleeps between the split window events to make sure the prompts
# wrap correctly. I kid you not. If you set this too low, it will look
# like:
PANEWAIT=2

# Double vertical window on the left, with one of them having a
# single-character width because of the monitor edge issues
tmux new-session -d -s "$SESSIONNAME" 'vim file5_u430_201610111309.txt'
sleep $PANEWAIT

tmux new-window
sleep $PANEWAIT

tmux split-window -h 
sleep $PANEWAIT

tmux split-window -v
sleep $PANEWAIT

tmux select-pane -t 0
sleep $PANEWAIT

tmux split-window -h 
sleep $PANEWAIT

tmux select-pane -t 0
sleep $PANEWAIT


# After the session loads, issue the command below with the left most
# pane focused
#resize-pane -L 65 
# Then clear the command line with:
# export PS1=; clear
#to get that 1-char wide left pane automate it here when you figure out
# how to get it to work from a script

tmux -2 new-session -t "$SESSIONNAME"

